#腾讯云配置
tencent-cloud:
 secretId: AKIDdzENeziCaovsjQkRAxgIHEMRM622f4xMI5
 secretKey: 9A3mSxHsMnBUiwAQYWAl33Dd4a7NaOD0hx
 requestMethod: GET
 defaultRegion: bj
#腾讯文智自然语言处理参数配置
lexical-analysis-config:
 code: 2097152
 type: 0

server:
  port: 8090
#redis配置
spring:
  redis:
    host: localhost
    port: 6379
    database: 0



